fragment imageHotspot on SanityImageHotspot {
  x
  y
  width
  height
}

fragment imageCrop on SanityImageCrop {
  top
  bottom
  left
  right
}

fragment seoFragment on Seo {
  metaTitle
  metaDesc
  keywords
  shareGraphic {
    asset {
      url
      altText
    }
  }
}

fragment imageAsset on SanityImageAsset {
  url
  altText
  metadata {
    lqip
  }
}

fragment NavigationSection on NavigationSection {
  target {
    ... on Page {
      title
      slug {
        current
      }
    }
    title
  }
  children {
    title
    target {
      ... on Page {
        title
        slug {
          current
        }
      }
      ... on Category {
        title
        slug {
          current
        }
      }
      ... on Nursery {
        title
        slug {
          current
        }
      }
    }
  }
}

fragment ContentBlockFragment on ContentBlocks {
  contentblocks {
    ... on Hero {
      titleRaw
      subtitleRaw
      heroImage {
        image {
          asset {
            ...imageAsset
            metadata {
              lqip
            }
          }
          hotspot {
            ...imageHotspot
          }
          crop {
            ...imageCrop
          }
        }
      }
      heroCards {
        title
        subtitle
        colourTheme
        link {
          label
          href
        }
      }
      buttons {
        label
        href
      }
    }
    ... on CardList {
      title
      subtitle
      scallopedTop
      cards {
        title
        subtitle
        image {
          image {
            asset {
              ...imageAsset
              metadata {
                lqip
              }
            }
            hotspot {
              ...imageHotspot
            }
            crop {
              ...imageCrop
            }
          }
        }
        link {
          label
          href
        }
      }
    }
    ... on TextWithImage {
      scallopedTop
      textRaw
      links {
        label
        href
      }
      image {
        image {
          asset {
            ...imageAsset
            metadata {
              lqip
            }
          }
          hotspot {
            ...imageHotspot
          }
          crop {
            ...imageCrop
          }
        }
      }
    }
    ... on ReviewsCarousel {
      scallopedTop
      scallopedBottom
      title
    }
    ... on StaffCards {
      title
      textRaw
      links {
        label
        href
      }
      layout
      staffProfiles {
        ... on Staff {
          name
          jobTitle
          biographyRaw
          profileImage {
            image {
              asset {
                ...imageAsset
              }
              hotspot {
                ...imageHotspot
              }
              crop {
                ...imageCrop
              }
            }
          }
        }
      }
    }
    ... on LocationDetails {
      title
    }
    ... on Fees {
      scallopedTop
      scallopedBottom
      title
      subtitle
      fees {
        _key
        label
        cost
      }
      links {
        _key
        label
        href
      }
      reverseLayout
    }
    ... on Downloads {
      downloads {
        _key
        label
        file {
          asset {
            url
          }
        }
      }
    }
    ... on SimpleHero {
      topLine
      title
      subtitle
      buttons {
        label
        href
      }
    }
    ... on Gallery {
      images {
        label
        altText
        image {
          _key
          asset {
            ...imageAsset
          }
          hotspot {
            ...imageHotspot
          }
          crop {
            ...imageCrop
          }
        }
      }
    }
    ... on GridGallery {
      gallerySections {
        _key
        title
        subtitle
        images {
          image {
            _key
            asset {
              ...imageAsset
            }
            hotspot {
              ...imageHotspot
            }
            crop {
              ...imageCrop
            }
          }
        }
      }
    }
  }
}

query GetNavigationById($id: ID!) {
  Navigation(id: $id) {
    _id
    title
    sections {
      ...NavigationSection
    }
  }
}

query GetCategoryBySlug($slug: String) {
  allCategory(where: { slug: { current: { eq: $slug } } }) {
    _id
    title
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

## "sort": [ { "_createdAt": "DESC" } ]
query GetAllPosts(
  $where: PostFilter
  $sort: [PostSorting!]
  $limit: Int
  $offset: Int
) {
  allPost(where: $where, sort: $sort, offset: $offset, limit: $limit) {
    title
    contentRaw
    _createdAt
    articleImage {
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    slug {
      current
    }
    category {
      title
      slug {
        current
      }
    }
  }
}

query GetPostBySlug($slug: String) {
  allPost(where: { slug: { current: { eq: $slug } } }) {
    title
    contentRaw
    _createdAt
    seo {
      ...seoFragment
    }
  }
}

query GetPostsByCategory($slug: String) {
  allPost(where: { category: { slug: { current: { eq: $slug } } } }) {
    title
    contentRaw
    _createdAt
    articleImage {
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    category {
      title
      slug {
        current
      }
    }
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

query GetAllStaff {
  allStaff {
    _id
    _type
    name
    jobTitle
    profileImage {
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    biographyRaw
  }
}

query GetAllFeedback {
  allFeedback {
    _id
    name
    starRating
    contentRaw
  }
}

query GetAllNurseries {
  allNursery(sort: { location: ASC }) {
    _id
    title
    location
    address
    phoneNumber
    email
    directionsLink
    mapsLink
    formId
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

query GetAllRooms {
  allPage(where: { pageType: { eq: "room" } }) {
    _id
    title
    slug {
      current
    }
  }
}

query GetPageBySlug($slug: String) {
  page: allPage(where: { slug: { current: { eq: $slug } } }) {
    _id
    _type
    title
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
    seo {
      ...seoFragment
    }
  }
}

query GetNurseryBySlug($slug: String) {
  page: allNursery(where: { slug: { current: { eq: $slug } } }) {
    _id
    _type
    title
    location
    address
    phoneNumber
    email
    directionsLink
    mapsLink
    formId
    contentBlocks {
      ... on ContentBlocks {
        ...ContentBlockFragment
      }
    }
    seo {
      ...seoFragment
    }
  }
}

query GetAllBanners {
  allBanner {
    _id
    content
    darkTextTheme
    backgroundColour {
      label
      value
    }
    links {
      label
      href
    }
  }
}
