fragment imageHotspot on SanityImageHotspot {
  x
  y
  width
  height
}

fragment imageCrop on SanityImageCrop {
  top
  bottom
  left
  right
}

fragment seoFragment on Seo {
  metaTitle
  metaDesc
  keywords
  shareGraphic {
    asset {
      url
      altText
    }
  }
}

fragment imageAsset on SanityImageAsset {
  url
  altText
  metadata {
    lqip
  }
}

fragment NavigationSection on NavigationSection {
  target {
    ... on Page {
      title
      slug {
        current
      }
    }
    title
  }
  children {
    title
    target {
      ... on Page {
        title
        slug {
          current
        }
      }
      ... on Category {
        title
        slug {
          current
        }
      }
      ... on Nursery {
        title
        slug {
          current
        }
      }
    }
  }
}

query GetNavigationById($id: ID!) {
  Navigation(id: $id) {
    _id
    title
    sections {
      ...NavigationSection
    }
  }
}

query GetPageBySlug($slug: String) {
  allPage(where: { slug: { current: { eq: $slug } } }) {
    _type
    title
    seo {
      ...seoFragment
    }
  }
}

query GetCategoryBySlug($slug: String) {
  allCategory(where: { slug: { current: { eq: $slug } } }) {
    _id
    title
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

## "sort": [ { "_createdAt": "DESC" } ]
query GetAllPosts(
  $where: PostFilter
  $sort: [PostSorting!]
  $limit: Int
  $offset: Int
) {
  allPost(where: $where, sort: $sort, offset: $offset, limit: $limit) {
    title
    contentRaw
    _createdAt
    slug {
      current
    }
    category {
      title
      slug {
        current
      }
    }
  }
}

query GetPostBySlug($slug: String) {
  allPost(where: { slug: { current: { eq: $slug } } }) {
    title
    contentRaw
    _createdAt
    seo {
      ...seoFragment
    }
  }
}

query GetPostsByCategory($slug: String) {
  allPost(where: { category: { slug: { current: { eq: $slug } } } }) {
    title
    category {
      title
      slug {
        current
      }
    }
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

query GetAllStaff {
  allStaff {
    _id
    _type
    name
    jobTitle
    profileImage {
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    biographyRaw
  }
}

query GetAllFeedback {
  allFeedback {
    _id
    name
    starRating
    contentRaw
  }
}

query GetAllNurseries {
  allNursery(sort: { location: ASC }) {
    _id
    title
    location
    address
    phoneNumber
    email
    directionsLink
    mapsLink
    slug {
      current
    }
    seo {
      ...seoFragment
    }
  }
}

query GetAllRooms {
  allPage(where: { pageType: { eq: "room" } }) {
    _id
    title
    subtitle
    slug {
      current
    }
  }
}

query GetHomepage($slug: String) {
  rooms: allPage(where: { pageType: { eq: "room" } }) {
    _id
    title
    subtitle
    slug {
      current
    }
  }
  staff: allStaff(where: { name: { in: ["Sarah", "Shellby", "Paula"] } }) {
    _id
    name
    jobTitle
    profileImage {
      image {
        asset {
          ...imageAsset
        }
        hotspot {
          ...imageHotspot
        }
        crop {
          ...imageCrop
        }
      }
    }
    biographyRaw
  }
  page: allPage(where: { slug: { current: { eq: $slug } } }) {
    _id
    _type
    title
    seo {
      ...seoFragment
    }
  }
}
